"""
GCode generator for the hollow cylinder extension.
Produces a ready-to-print GCode file for Ender 3 / similar FDM printer.

Print settings:
  Layer height   : 0.2 mm
  Nozzle         : 0.4 mm
  Filament       : 1.75 mm PLA
  Print speed    : 50 mm/s (perimeters), 25 mm/s (first layer)
  Bed temp       : 60 °C
  Nozzle temp    : 210 °C
  Perimeters     : 5  (fills the 2 mm wall exactly with 0.4 mm nozzle)
  No infill needed (solid walls)
"""

import math

# ── Geometry ─────────────────────────────────────────────────────────────────
INNER_RADIUS    = 7.8       # mm
OUTER_RADIUS    = 9.8       # mm
HEIGHT          = 25.0      # mm
SEGMENTS        = 128       # arc resolution per layer

# ── Print settings ────────────────────────────────────────────────────────────
LAYER_HEIGHT    = 0.2       # mm
NOZZLE_DIA      = 0.4       # mm
FILAMENT_DIA    = 1.75      # mm
PERIMETERS      = 5
PRINT_SPEED     = 50        # mm/s
FIRST_SPEED     = 25        # mm/s
TRAVEL_SPEED    = 150       # mm/s
BED_TEMP        = 60
NOZZLE_TEMP     = 210
RETRACT_LEN     = 1.0       # mm
RETRACT_SPEED   = 45        # mm/s

# Extrusion cross-section area
FILAMENT_AREA   = math.pi * (FILAMENT_DIA / 2) ** 2
EXTRUSION_WIDTH = NOZZLE_DIA * 1.2  # typical extrusion width multiplier

def extrusion_for_move(dx, dy, layer_h=LAYER_HEIGHT):
    dist = math.sqrt(dx*dx + dy*dy)
    vol  = dist * layer_h * EXTRUSION_WIDTH
    return vol / FILAMENT_AREA

def ring_points(radius, segments, z):
    pts = []
    for i in range(segments):
        a = 2 * math.pi * i / segments
        pts.append((radius * math.cos(a), radius * math.sin(a), z))
    return pts

def write_ring(f, pts, speed, e_total, retract=False):
    # Move to start without extruding
    x0, y0, z0 = pts[0]
    if retract:
        f.write(f"G1 E{e_total - RETRACT_LEN:.5f} F{RETRACT_SPEED*60:.0f}\n")
    f.write(f"G0 X{x0:.3f} Y{y0:.3f} F{TRAVEL_SPEED*60:.0f}\n")
    if retract:
        f.write(f"G1 E{e_total:.5f} F{RETRACT_SPEED*60:.0f}\n")
    # Extrude around ring
    for i in range(1, len(pts) + 1):
        x1, y1, _ = pts[i % len(pts)]
        dx = x1 - pts[(i-1) % len(pts)][0]
        dy = y1 - pts[(i-1) % len(pts)][1]
        e_total += extrusion_for_move(dx, dy)
        f.write(f"G1 X{x1:.3f} Y{y1:.3f} E{e_total:.5f} F{speed*60:.0f}\n")
    return e_total

def generate(output="cylinder_extension.gcode"):
    layers = int(round(HEIGHT / LAYER_HEIGHT))
    cx, cy = 100.0, 100.0   # center on bed (Ender 3: 220x220)

    with open(output, "w") as f:
        # ── Start GCode ──────────────────────────────────────────────────────
        f.write(f"""; Cylinder Extension — fits over 15.4mm OD cylinder
; Inner dia: {INNER_RADIUS*2:.1f}mm  Outer dia: {OUTER_RADIUS*2:.1f}mm  Height: {HEIGHT}mm
; Generated by generate_gcode.py
M104 S{NOZZLE_TEMP}        ; set nozzle temp (no wait)
M140 S{BED_TEMP}           ; set bed temp (no wait)
M190 S{BED_TEMP}           ; wait for bed
M109 S{NOZZLE_TEMP}        ; wait for nozzle
G28                         ; home all axes
G90                         ; absolute positioning
M82                         ; absolute extruder
G92 E0                      ; reset extruder
; Purge line
G1 Z0.3 F1200
G1 X10 Y10 F3000
G1 X10 Y200 E15 F900
G92 E0
G1 Z0.5 F1200
""")
        e_total = 0.0
        first_layer = True

        for layer_num in range(layers):
            z = (layer_num + 1) * LAYER_HEIGHT
            speed = FIRST_SPEED if first_layer else PRINT_SPEED
            f.write(f"\n; Layer {layer_num+1} z={z:.2f}\n")
            f.write(f"G1 Z{z:.2f} F1200\n")

            # Print each perimeter ring from outer → inner
            for p in range(PERIMETERS):
                r = OUTER_RADIUS - p * EXTRUSION_WIDTH
                if r < INNER_RADIUS + EXTRUSION_WIDTH / 2:
                    break
                pts = [(cx + r*math.cos(2*math.pi*i/SEGMENTS),
                        cy + r*math.sin(2*math.pi*i/SEGMENTS),
                        z) for i in range(SEGMENTS)]
                e_total = write_ring(f, pts, speed, e_total, retract=(p == 0))

            first_layer = False

        # ── End GCode ────────────────────────────────────────────────────────
        f.write(f"""
; End
M104 S0         ; nozzle off
M140 S0         ; bed off
G91             ; relative
G1 Z10 F1200    ; lift
G90             ; absolute
G1 X10 Y200 F3000 ; present print
M84             ; motors off
""")

    print(f"Saved {output}")
    print(f"  Layers  : {layers}")
    print(f"  Est E   : {e_total:.1f} mm filament")
    vol_cm3 = (e_total * FILAMENT_AREA) / 1000
    print(f"  Est vol : {vol_cm3:.1f} cm³  (~{vol_cm3*1.24:.1f}g PLA)")

if __name__ == "__main__":
    generate()
